# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u7522\u54c1\u540d\u7a31')),
                ('description', models.TextField(verbose_name='\u7522\u54c1\u6558\u8ff0')),
                ('quantity', models.IntegerField(verbose_name='\u5eab\u5b58\u6578\u91cf')),
                ('price', models.IntegerField(verbose_name='\u50f9\u683c')),
            ],
        ),
    ]
